POST http://localhost:8080/api/tickets/purchase?email=mygamesiti0@gmail.com
Content-Type: application/json

{
  "eventId": 1,
  "ticketCount": 2,
  "cardNumber": "4111111111111111",
  "cardHolder": "IVAN IVANOV",
  "expiryDate": "12/25",
  "cvv": "123"
}